learning_rate: 0.003234
gamma: 0.9773
buffer_size: 100000
epsilon_min: 0.06469
epsilon_max: 1.
epsilon_decay_period: 21381
epsilon_delay_decay: 54
batch_size: 800
gradient_steps: 6
update_target_strategy: "replace"
update_target_freq: 709
update_target_tau: 0.005