learning_rate: 0.001
gamma: 1
buffer_size: 100000
epsilon_min: 0.02
epsilon_max: 1.
epsilon_decay_period: 20000
epsilon_delay_decay: 100
batch_size: 800
gradient_steps: 6
update_target_strategy: "replace"
update_target_freq: 400
update_target_tau: 0.005