method: bayes
    
metric : 
    name: score_agent_dr
    goal: maximize   

parameters :
    learning_rate:
        distribution: log_uniform_values
        min: 0.0005
        max: 0.005
    epsilon_min:
        min: 0.02
        max: 0.08
        distribution: uniform
    epsilon_decay_period:
        min: 15000
        max: 25000
        distribution: int_uniform
    update_target_freq:
        min: 400
        max: 1000
        distribution: int_uniform
    gamma:
        min: 0.95
        max: 1.0
        distribution: uniform
