method: bayes
    
metric : 
    name: score_agent_dr
    goal: maximize   

parameters :
    learning_rate:
        distribution: log_uniform_values
        min: 0.0001
        max: 0.01
    epsilon_min:
        min: 0.01
        max: 0.05
        distribution: uniform
    epsilon_decay_period:
        min: 10000
        max: 30000
        distribution: int_uniform
    epsilon_delay_decay:
        min: 50
        max: 150
        distribution: int_uniform
    gradient_steps:
        min: 3
        max: 5
        distribution: int_uniform
    update_target_freq:
        min: 200
        max: 600
        distribution: int_uniform
    gamma:
        min: 0.95
        max: 1.0
        distribution: uniform
