method: bayes
    
metric : 
    name: score_agent_dr
    goal: maximize   

parameters :
    learning_rate:
        distribution: log_uniform_values
        min: 0.00001
        max: 0.1
    epsilon_min:
        min: 0.01
        max: 0.05
        distribution: uniform
    epsilon_decay_period:
        min: 10000
        max: 30000
        distribution: int_uniform
    epsilon_delay_decay:
        min: 50
        max: 150
        distribution: int_uniform
    gradient_steps:
        min: 3
        max: 5
        distribution: int_uniform
    update_target_strategy:
        values: ["replace", "ema"] 
    update_target_freq:
        min: 200
        max: 600
        distribution: int_uniform
    update_target_tau:
        min: 0.001
        max: 0.01
        distribution: uniform
    gamma:
        min: 0.95
        max: 1.0
        distribution: uniform
    buffer_size:
        values: [50000, 100000, 150000, 200000]
